#!/bin/bash
# rt-stats: generate statistics of your RequestTracker 
# Copyright: (C) 2011 Florian Baumann <flo@noqqe.de>
# License: GPL-3 <http://www.gnu.org/licenses/gpl-3.0.txt>
# Date: Tuesday 2011-04-12

### Include configuration
if [ -e conf/rt-stats.conf ]; then
    source conf/rt-stats.conf
    if [ -e conf/rt-stats.local ]; then
        source conf/rt-stats.local
    fi
else
    echo "Error: Could not find config file conf/rt-stats.conf"
    exit 1
fi

### Load modules

# monthly resolved by user
echo "Resolved Ticket Statistic for this Month ($(date +%Y-%m))"
echo "---------------------------------------------------"
source modules/user-this-month.bash
echo

# yearly resolved by user
echo "Resolved Ticket Statistic for this Year ($(date +%Y))"
echo "---------------------------------------------------"
source modules/user-this-year.bash
echo 

# yearly resolved by user
echo "Ticket Status for this Month ($(date +%Y-%m))"
echo "---------------------------------------------------"
source modules/ticket-actions-this-month.bash 
echo 

# yearly resolved by user
echo "Ticket Status for this Year ($(date +%Y))"
echo "---------------------------------------------------"
source modules/ticket-actions-this-year.bash 
echo 

# yearly resolved by user
echo "Queues for this Month ($(date +%Y-%m))"
echo "---------------------------------------------------"
source modules/queue-this-month.bash
echo 

# yearly resolved by user
echo "Queues for this Year ($(date +%Y))"
echo "---------------------------------------------------"
source modules/queue-this-year.bash
echo 

# yearly resolved by user
echo "Most Active Creators for this Month ($(date +%Y-%m))"
echo "---------------------------------------------------"
source modules/creators-this-month.bash 
echo 

# yearly resolved by user
echo "Most Active Creators for this Year ($(date +%Y))"
echo "---------------------------------------------------"
source modules/creators-this-year.bash 
echo 

# monthly activity by user 
echo "Activity by User ($(date +%Y))"
echo "---------------------------------------------------"
source modules/user-activity.bash 
echo 
