#!/bin/bash
# rt-stats: generate statistics of your RequestTracker 
# Copyright: (C) 2011 Florian Baumann <flo@noqqe.de>
# License: GPL-3 <http://www.gnu.org/licenses/gpl-3.0.txt>
# Date: Tuesday 2011-04-12

### Include configuration
if [ -e conf/rt-stats.conf ]; then
    source conf/rt-stats.conf
    if [ -e conf/rt-stats.local ]; then
        source conf/rt-stats.local
    fi
else
    echo "Error: Could not find config file conf/rt-stats.conf"
    exit 1
fi

### Load modules

# monthly resolved by user
echo "Resolved Ticket Statistic for this Month$(date +%Y-%m)"
echo "---------------------------------------------------"
source modules/most-active-user-this-month.bash
echo

# yearly resolved by user
echo "Resolved Ticket Statistic for this Year $(date +%Y)"
echo "---------------------------------------------------"
source modules/most-active-user-this-year.bash
echo 

# yearly resolved by user
echo "Most Ticket Status for this Month $(date +%Y-%m)"
echo "---------------------------------------------------"
source modules/most-ticket-actions-this-month.bash 
echo 

# yearly resolved by user
echo "Most Ticket Status for this Year $(date +%Y)"
echo "---------------------------------------------------"
source modules/most-ticket-actions-this-year.bash 
echo 

# yearly resolved by user
echo "Most Active Queue for this Month $(date +%Y-%m)"
echo "---------------------------------------------------"
source modules/most-active-queue-this-month.bash
echo 

# yearly resolved by user
echo "Most Active Queue for this Year $(date +%Y)"
echo "---------------------------------------------------"
source modules/most-active-queue-this-year.bash
echo 

# yearly resolved by user
echo "Most Active Creators for this Month $(date +%Y-%m)"
echo "---------------------------------------------------"
source modules/most-active-creators-this-month.bash 
echo 

# yearly resolved by user
echo "Most Active Creators for this Year $(date +%Y)"
echo "---------------------------------------------------"
source modules/most-active-creators-this-year.bash 
echo 
